### ISSUE TITLE
ScanImage2017b compatabilty?

### ISSUE THREAD

**Issue by MMathisLab** [atlab/scanreader#1]
Hi @ecobost, is this compatible with SI2017?

**Comment by ecobost** [comment]
Yes, I've tested it with 5.1, 5.2, 2016a/b and 2017a/b. We also keep a Matlab version [here](https://github.com/ecobost/scanreader-matlab).

**Comment by MMathisLab** [comment]
Hi @ecobost - any way to update it for ScanImage2018a?

**Comment by MMathisLab** [comment]
based on Issue #2 I changed the code for scan.py and core.py - hopefully these work (but will leave here for you to test/look at if you like!) 

[scanreader_2018aAdded.zip](https://github.com/atlab/scanreader/files/2215575/scanreader_2018aAdded.zip)
