### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by horsto** [atlab/scanreader#2]
Hi, I am getting the following error when trying to read a scanimage .tif: 
`ScanImageVersionError: Sorry, ScanImage version 5.3 is not supported
`
Is it possible to extend compatibility to 5.3 (assuming not much has changed?)?
Thank you!

**Comment by ecobost** [comment]
If it's the same as SI 5.2, adding it should the pretty easy: create a Scan5Point3 in scans.py that inherits from Scan5Point2 and has no additional methods; and add 5.3 as an option in core.py. Could you send me a small sample Tiff just so I can check it would work

**Comment by horsto** [comment]
Hey, sorry for the very late reply. Here is a .tif stack example. Would be great if you could add support. Thanks!
[TEST_00006_00001.zip](https://github.com/atlab/scanreader/files/1864051/TEST_00006_00001.zip)

**Comment by ecobost** [comment]
Added  in https://github.com/atlab/scanreader/commit/5ad8109f39849a71d8e24187d7f4c0a50443646c

**Comment by horsto** [comment]
Great, thanks a lot!
