### ISSUE TITLE
Add support for ScanImage version 5.5

### ISSUE THREAD

**Issue by horsto** [atlab/scanreader#7]
Hi! I am relying on scanreader for my analysis pipeline and I am really happy with it! 
I recently updated to v5.5 and I am now running into errors 
`ScanImageVersionError: Sorry, ScanImage version 5.5 is not supported
`  
Could you add support for scanImage version 5.5 tifs? I think that nothing has drastically changed in the format.
Thanks a lot!

**Comment by ecobost** [comment]
Added it. Test it. If something needs fixing, send me a sample scan so I can fix it

**Comment by horsto** [comment]
Fantastic, seems to work fine! Thanks a lot!
