### ISSUE TITLE
Support ScanImage version 5.7

### ISSUE THREAD

**Issue by horsto** [atlab/scanreader#9]
Hi, is it possible to enable support for Scanimage 5.7 tifs? 
This would be super helpful - and my guess is that not much has changed in the structure. 
`ScanImageVersionError: Sorry, ScanImage version 5.7 is not supported`

**Comment by ecobost** [comment]
Hi @horsto, could you change the code and open a PR for it. It should be pretty simple, almost exactly like this commit: https://github.com/atlab/scanreader/commit/ee8cfaf094e6d3bf206ebd8807d5ba50bde01978-
I don't think there will be breaking changes: http://scanimage.vidriotechnologies.com/display/SI2019/README

**Comment by horsto** [comment]
Ok! I just made a PR (https://github.com/atlab/scanreader/pull/10) and hope that's ok!

**Comment by ecobost** [comment]
accepted the PR
